package io.github.cjustinn.specialisedworkforce;

public enum JobAttributeType {
    BONUS_BLOCK_DROPS,
    DURABILITY_SAVE,
    CRAFTING_EXPERIENCE_GAIN,
    ANVIL_COST_REDUCTION,
    BONUS_FISHING_DROPS,
    BONUS_MOB_DROPS,
    ENCHANTING_LEVEL_BOOST,
    ENCHANTING_COST_REDUCTION,
    POTION_DURATION_BOOST
}
